(ang. Eigene Decomposition / Spectral Decomposition)


In [ ]:
import numpy as np
from scipy import linalg

In [70]:
from tqdm import tqdm

In [32]:
A = np.random.rand(3,3)

In [34]:
def power_method(A, eps=1e-5, maxIt=100000):
    n = len(A)
    v_k = np.array([1/n] * n)
    delta = 1
    for i in range(maxIt):
        if(delta < eps):
            break
        v_kk = A @ v_k
        lambda_k = np.linalg.norm(v_k, np.inf)
        v_kk = v_kk / lambda_k
        delta = np.linalg.norm(v_k - v_kk)
        v_k = v_kk
    return v_k / np.linalg.norm(v_k)

In [35]:
power_method(A)

array([ 0.6418389 ,  0.43066188,  0.63448654])

In [87]:
np.linalg.eig(A)[1].transpose()[0]

array([ 0.64183899,  0.4306624 ,  0.6344861 ])

In [84]:
def raileigh(x, A):
    return (x.transpose() @ A @ x) / (x.transpose() @ x)

In [92]:
def inverse_power_method(A, eps=1e-5, maxIt=10000, sigma=1):
    n = len(A)
    v_k = np.array([1/n] * n)
    B = A - sigma * np.eye(n)
    delta = 1
    
    solver = linalg.lu_factor(B)
    
    for i in tqdm(range(maxIt)):
        if(delta < eps):
            break
        v_kk = linalg.lu_solve(solver, v_k)
        v_kk = v_kk / np.linalg.norm(v_kk)
        delta = np.linalg.norm(v_k - v_kk)
        v_k = v_kk
    lambda_k = raileigh(v_k, A)
    return v_k / np.linalg.norm(v_k), lambda_k

In [93]:
inverse_power_method(A)

  0%|          | 0/10000 [00:00<?, ?it/s]


(array([ 0.64183729,  0.43066191,  0.63448815]), 1.4430730569809564)

In [95]:
np.linalg.solve

<function numpy.linalg.linalg.solve>

In [113]:
def Rayleigh_iloraz(A, sigma=0, eps=1e-5, maxIt=10000):
    lambda_k = sigma
    n = len(A)
    delta = 1
    v_k = np.array([1/n] * n)
    for i in range(maxIt):
        if delta < eps:
            break;
        B = A - lambda_k * np.eye(len(A))
        v_kk = np.linalg.solve(B, v_k)
        v_kk = v_kk / np.linalg.norm(v_kk)
        lambda_k = raileigh(v_k, A)
        delta = np.linalg.norm(v_k - v_kk)
        v_k = v_kk
        
    return v_k

In [114]:
Rayleigh_iloraz(A)

array([ 0.64183899,  0.4306624 ,  0.6344861 ])